import { HomeContainer, Product } from "@/styles/pages/home";
import Head from "next/head";
import Image from "next/image";

import camiseta1 from "../assets/camisetas/1.png";

export default function Home() {
  return (
    <>
      <Head>
        <title>Ignite Shop</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomeContainer>
        <Product>
          <Image src={camiseta1} width={520} height={480} alt="" />
          <footer>
            <strong>Camiseta x</strong>
            <span>R$ 29,99</span>
          </footer>
        </Product>
        <Product>
          <Image src={camiseta1} width={520} height={480} alt="" />
          <footer>
            <strong>Camiseta x</strong>
            <span>R$ 29,99</span>
          </footer>
        </Product>
      </HomeContainer>
    </>
  );
}
